--- #YAML:1.0
name:               SweetPea-Style-Default
version:            0.01
abstract:           The great new SweetPea::Style::Default!
author:
    - Al Newkirk <al.newkirk@awnstudio.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::FormValidator:  0
    DBIx::Class:          0
    DBIx::Class::Schema::Loader:  0
    Email::Stuff:         0
    Template:             0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
